name: PowerShell Linting

on:
  push:
    branches: [ main ]
    paths:
      - '**.ps1'
  pull_request:
    branches: [ main ]
    paths:
      - '**.ps1'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/powershell:latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module -Name PSScriptAnalyzer -Force
      
      - name: Lint with PSScriptAnalyzer
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path . -Recurse -Settings PSScriptAnalyzerSettings.psd1 -OutVariable issues
          $errors   = $issues.Where({$_.Severity -eq 'Error'})
          $warnings = $issues.Where({$_.Severity -eq 'Warning'})
          
          if ($errors) {
              Write-Error "There were $($errors.Count) errors and $($warnings.Count) warnings total." -ErrorAction Stop
          } else {
              Write-Output "There were $($errors.Count) errors and $($warnings.Count) warnings total."
          }
